version: "3.8" 
services:
  dev-db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
